apiVersion: v1
kind: Service
metadata:
  name: nginx-workshop-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-default-protocol: http
    service.beta.kubernetes.io/linode-loadbalancer-port-443: '{ "tls-secret-name": "mqtttest", "protocol": "https" }'
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-workshop
  sessionAffinity: None
